version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    # Steps to the job
    steps:
      - run: 
          name: Set up environment variables into .env
          command: |
            echo $USERNAME
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install --with-deps chrome
      - run:
          name: Run test
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test --reporter=junit --project=chromium
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test
