name: Playwright Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Newman and HTML Extra Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chrome
    
    - name: Setup environment variables
      run: |
        echo "Setting up environment variables..."
        echo "TESTOMATIO=${TESTOMATIO}"
        echo "TESTOMATIO env var length: ${#TESTOMATIO}"
        echo "TESTOMATIO env var first 10 chars: ${TESTOMATIO:0:10}..."
        echo "TESTOMATIO=${TESTOMATIO}" >> .env
        echo "USERNAME=${USERNAME}" >> .env
        echo "PASSWORD=${PASSWORD}" >> .env
    
    - name: Run Playwright tests
      run: TESTOMATIO=$TESTOMATIO npm run tests
      env:
        TESTOMATIO: ${{ secrets.TESTOMATIO }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
          allure-results/
        retention-days: 30 